AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CFN Stack to deploy a Resource Explorer Index and View.
  Creates an AGGREGATOR or LOCAL index and associates a default view.

Parameters:
  AggregatorIndexRegion:
    Type: String
    Description: Region where the aggregator index will be deployed.

Conditions:
  IsAggregatorIndex: !Equals [!Ref "AWS::Region", !Ref AggregatorIndexRegion]

Resources:
  Index:
    Type: AWS::ResourceExplorer2::Index
    Properties:
      Type: !If [IsAggregatorIndex, "AGGREGATOR", "LOCAL"]
      Tags:
        Purpose: ResourceExplorer CFN Stack

  View:
    Type: AWS::ResourceExplorer2::View
    DependsOn: Index
    Properties:
      ViewName: !If
        - IsAggregatorIndex
        - "All-resources-across-AWS-regions"
        - !Sub "Regional-resource-view-${AWS::Region}"
      IncludedProperties:
        - Name: tags
      Tags:
        Purpose: ResourceExplorer CFN Stack

  DefaultViewAssociation:
    Type: AWS::ResourceExplorer2::DefaultViewAssociation
    DependsOn: View
    Properties:
      ViewArn: !Ref View

Outputs:
  ResourceExplorerIndexArn:
    Description: ARN of the created Resource Explorer Index
    Value: !GetAtt Index.Arn

  ResourceExplorerViewName:
    Description: Name of the Resource Explorer View created by this stack
    Value: !If
      - IsAggregatorIndex
      - "All-resources-across-AWS-regions"
      - !Sub "Regional-resource-view-${AWS::Region}"
