AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Deploys a Resource Explorer AGGREGATOR index and a default organization-wide view.

Parameters:
  OrganizationArn:
    Type: String
    Description: ARN of the AWS Organization (e.g. arn:aws:organizations::111122223333:organization/o-xxxxxxxxxx)

  ViewName:
    Type: String
    Default: OrganizationWideView
    Description: Name of the Resource Explorer view

Resources:
  Index:
    Type: AWS::ResourceExplorer2::Index
    Properties:
      Type: AGGREGATOR
      Tags:
        Purpose: ResourceExplorer CFN Stack

  View:
    Type: AWS::ResourceExplorer2::View
    DependsOn: Index
    Properties:
      ViewName: !Ref ViewName
      IncludedProperties:
        - Name: tags
      Scope: !Ref OrganizationArn
      Tags:
        Purpose: ResourceExplorer CFN Stack

  DefaultViewAssociation:
    Type: AWS::ResourceExplorer2::DefaultViewAssociation
    DependsOn: View
    Properties:
      ViewArn: !Ref View

Outputs:
  ResourceExplorerIndexArn:
    Description: ARN of the Resource Explorer Index
    Value: !GetAtt Index.Arn

  ResourceExplorerViewName:
    Description: Name of the Resource Explorer View
    Value: !Ref View
